/* -------------------------------------------------------------------------
   completions.js — declarative Monaco completion DATA for the Badgeware editor.
   Pure data (no logic): the toCompletionItem() mapper lives in editor.js, its
   only consumer.

   Exports:
     BADGEWARE_GLOBALS  — top-level identifiers: Badgeware API + MicroPython
     MEMBERS            — member completions, keyed by the identifier before "."

   Sources:
     simulator/filesystem/badgeware/__init__.py
     simulator/filesystem/badgeware/badge.py    (+ text, sprite, math, state, rtc)
     MicroPython 1.x built-in functions / types / exceptions / modules
   ------------------------------------------------------------------------- */

export const BADGEWARE_GLOBALS = [

  // -- Display mode flags ----------------------------------------------------
  { label: 'LORES',         kind: 'Constant', detail: '0b00',     doc: 'Low-resolution mode: 160×120 pixels.' },
  { label: 'HIRES',         kind: 'Constant', detail: '0b01',     doc: 'High-resolution mode: 320×240 pixels.' },
  { label: 'VSYNC',         kind: 'Constant', detail: '0b10',     doc: 'Enable vertical sync.' },
  { label: 'FAST_UPDATE',   kind: 'Constant', detail: '3 << 4',   doc: 'Fast e-ink update speed (Badger).' },
  { label: 'FULL_UPDATE',   kind: 'Constant', detail: '0 << 4',   doc: 'Full/slow e-ink update (Badger).' },
  { label: 'MEDIUM_UPDATE', kind: 'Constant', detail: '2 << 4',   doc: 'Medium e-ink update speed (Badger).' },
  { label: 'DITHER',        kind: 'Constant', detail: '1 << 8',   doc: 'Enable dithering.' },

  // -- Button constants -------------------------------------------------------
  { label: 'BUTTON_A',      kind: 'Constant', detail: '0b010000', doc: 'Button A (left side button).' },
  { label: 'BUTTON_B',      kind: 'Constant', detail: '0b001000', doc: 'Button B (select / middle).' },
  { label: 'BUTTON_C',      kind: 'Constant', detail: '0b000100', doc: 'Button C (right side button).' },
  { label: 'BUTTON_UP',     kind: 'Constant', detail: '0b000010', doc: 'D-pad Up.' },
  { label: 'BUTTON_DOWN',   kind: 'Constant', detail: '0b000001', doc: 'D-pad Down.' },
  { label: 'BUTTON_HOME',   kind: 'Constant', detail: '0b100000', doc: 'Home / Boot button.' },

  // -- Anti-aliasing constants ------------------------------------------------
  { label: 'OFF', kind: 'Constant', detail: 'image.OFF', doc: 'Anti-aliasing disabled.' },
  { label: 'X2',  kind: 'Constant', detail: 'image.X2',  doc: 'Anti-aliasing: 2× supersample.' },
  { label: 'X4',  kind: 'Constant', detail: 'image.X4',  doc: 'Anti-aliasing: 4× supersample.' },

  // -- Global instances -------------------------------------------------------
  { label: 'screen',   kind: 'Variable', detail: 'image',      doc: 'The active display canvas. 160×120 in LORES, 320×240 in HIRES. Set screen.pen and call screen.clear(), screen.text(), screen.shape().' },
  { label: 'badge',    kind: 'Variable', detail: 'Badge',      doc: 'Badge hardware interface: buttons, battery, display mode, LEDs.' },
  { label: 'shape',    kind: 'Module',   detail: 'module',     doc: 'Shape factory (picovector): shape.rectangle(), shape.circle(), shape.custom(), …' },
  { label: 'color',    kind: 'Module',   detail: 'module',     doc: 'Color factory: color.rgb(r, g, b), color.hsv(h, s, v).' },
  { label: 'rom_font', kind: 'Variable', detail: 'ROMFonts',   doc: 'Built-in ROM pixel fonts. Access by name: rom_font.sins, rom_font.hungry, etc.' },
  { label: 'text',     kind: 'Module',   detail: '_text',      doc: 'Text layout utilities: text.draw(), text.scroll(), text.tokenise().' },
  { label: 'rtc',      kind: 'Variable', detail: 'RTC',        doc: 'Real-time clock: get/set datetime, alarms, countdown timers.' },
  { label: 'loop',     kind: 'Variable', detail: '_run | None', doc: 'Current animation loop context (None outside a loop). Provides loop.ticks and loop.progress.' },

  // -- Types / constructors ---------------------------------------------------
  { label: 'vec2',         kind: 'Class', insertText: 'vec2(${1:x}, ${2:y})',
    doc: '2D vector / point. Fields: .x, .y\nUsage: pos = vec2(80, 60)' },
  { label: 'rect',         kind: 'Class', insertText: 'rect(${1:x}, ${2:y}, ${3:w}, ${4:h})',
    doc: 'Rectangle. Fields: .x, .y, .w, .h\nUsage: bounds = rect(0, 0, 160, 120)' },
  { label: 'image',        kind: 'Class', insertText: 'image(${1:width}, ${2:height})',
    doc: 'Off-screen image buffer. Also a namespace: image.load(file), image.OFF / X2 / X4.' },
  { label: 'font',         kind: 'Class', insertText: 'font.load(${1:"path.af"})',
    doc: 'Vector font (.af files). Load with font.load(path).' },
  { label: 'pixel_font',   kind: 'Class', insertText: 'pixel_font.load(${1:"path.ppf"})',
    doc: 'Bitmap / pixel font (.ppf files). Load with pixel_font.load(path).' },
  { label: 'run',          kind: 'Class', insertText: 'run(${1:update})',
    doc: 'Run an animation loop. Use as a decorator @run or call run(fn). Optional: run(duration=ms).\nThe update() function is called every frame; return a value to exit.' },
  { label: 'SpriteSheet',  kind: 'Class', insertText: 'SpriteSheet(${1:file}, ${2:columns}, ${3:rows})',
    doc: 'Load a sprite sheet image. Args: file (path), columns (int), rows (int).\nAccess sprites via .sprite(x, y) or animations via .animation(x, y, count).' },
  { label: 'AnimatedSprite', kind: 'Class',
    doc: 'Animated sprite created by SpriteSheet.animation().\nMethods: .frame(index), .count().' },
  { label: 'State',        kind: 'Class',
    doc: 'Persistent JSON state (saved to /state/{app}.json).\nStatic methods: State.save(app, data), State.load(app, defaults), State.modify(app, data), State.delete(app).' },
  { label: 'brush',        kind: 'Class',
    doc: 'Advanced fill brush factory. Assign to screen.pen before drawing.\nbrush.gradient(type, x1, y1, x2, y2, stops), brush.image(img), brush.pattern(c1, c2, idx), brush.pixelate(n), brush.blur(r), brush.lighten(n), brush.darken(n).' },
  { label: 'mat3',         kind: 'Class', insertText: 'mat3()',
    doc: '3×3 transformation matrix for 2D transforms.\nMethods: .rotate(deg), .rotate_radians(rad), .translate(x, y), .scale(x, y), .multiply(other), .inverse().\nUsed with brush.gradient(…, transform=mat3()) and vec2.transform(mat3).' },
  { label: 'algorithm',    kind: 'Module',
    doc: 'Geometry algorithms.\nalgorithm.clip_line(p1, p2, rect) — clip a line to a rect.\nalgorithm.dda(point, angle, depth) — ray march on a grid.\nalgorithm.raycast(…) — 2D raycaster.' },

  // -- Global functions (Badgeware) -------------------------------------------
  { label: 'clamp',         kind: 'Function', insertText: 'clamp(${1:v}, ${2:vmin}, ${3:vmax})',
    doc: 'Clamp v between vmin and vmax. Returns a number.' },
  { label: 'rnd',           kind: 'Function', insertText: 'rnd(${1:v1})',
    doc: 'Random integer 0..v1 (inclusive), or rnd(v1, v2) for v1..v2.' },
  { label: 'frnd',          kind: 'Function', insertText: 'frnd(${1:v1})',
    doc: 'Random float 0.0..v1, or frnd(v1, v2) for v1..v2.' },
  { label: 'load_font',     kind: 'Function', insertText: 'load_font(${1:name})',
    doc: 'Load a font by name or path. Searches /rom/fonts, /system/assets/fonts, /fonts.\nReturns a font or pixel_font instance.' },
  { label: 'launch',        kind: 'Function', insertText: 'launch(${1:path})',
    doc: 'Launch an app module at the given path. Calls on_exit() if defined.' },
  { label: 'reset',         kind: 'Function', insertText: 'reset()',
    doc: 'Soft-reset the badge (machine.reset()).' },
  { label: 'set_brightness', kind: 'Function', insertText: 'set_brightness(${1:value})',
    doc: 'Set display backlight brightness. value: 0.0 (off) – 1.0 (full).' },
  { label: 'message',       kind: 'Function', insertText: 'message(${1:"title"}, ${2:"msg"})',
    doc: 'Draw an overlay message box. Args: title (str), msg (str), window=None.' },
  { label: 'fatal_error',   kind: 'Function', insertText: 'fatal_error(${1:"title"}, ${2:error})',
    doc: 'Show a fatal error overlay (switches to HIRES). Args: title (str), error (str or Exception).' },
  { label: 'file_exists',   kind: 'Function', insertText: 'file_exists(${1:path})',
    doc: 'Returns True if the path exists.' },
  { label: 'is_dir',        kind: 'Function', insertText: 'is_dir(${1:path})',
    doc: 'Returns True if the path is a directory.' },
  { label: 'free',          kind: 'Function', insertText: 'free()',
    doc: 'Print free heap memory in KB (with delta). Calls gc.collect() first.' },

  // -- MicroPython built-in functions ----------------------------------------
  { label: 'print',       kind: 'Function', insertText: 'print(${1:value})',
    doc: 'Print objects to stdout. Optional: sep, end, file.' },
  { label: 'len',         kind: 'Function', insertText: 'len(${1:obj})',
    doc: 'Return number of items in a container.' },
  { label: 'range',       kind: 'Function', insertText: 'range(${1:stop})',
    doc: 'Integer range. range(stop) or range(start, stop[, step]).' },
  { label: 'abs',         kind: 'Function', insertText: 'abs(${1:x})',
    doc: 'Absolute value of a number.' },
  { label: 'min',         kind: 'Function', insertText: 'min(${1:iterable})',
    doc: 'Smallest item. min(iterable) or min(a, b, …).' },
  { label: 'max',         kind: 'Function', insertText: 'max(${1:iterable})',
    doc: 'Largest item. max(iterable) or max(a, b, …).' },
  { label: 'sum',         kind: 'Function', insertText: 'sum(${1:iterable})',
    doc: 'Sum of all items in iterable.' },
  { label: 'round',       kind: 'Function', insertText: 'round(${1:x})',
    doc: 'Round to nearest integer, or to ndigits decimal places.' },
  { label: 'pow',         kind: 'Function', insertText: 'pow(${1:base}, ${2:exp})',
    doc: 'base raised to the power exp. Optional modulus argument.' },
  { label: 'divmod',      kind: 'Function', insertText: 'divmod(${1:a}, ${2:b})',
    doc: 'Return (a // b, a % b) as a tuple.' },
  { label: 'all',         kind: 'Function', insertText: 'all(${1:iterable})',
    doc: 'True if every element of iterable is truthy (or iterable is empty).' },
  { label: 'any',         kind: 'Function', insertText: 'any(${1:iterable})',
    doc: 'True if at least one element of iterable is truthy.' },
  { label: 'enumerate',   kind: 'Function', insertText: 'enumerate(${1:iterable})',
    doc: 'Return (index, value) pairs. Optional start argument.' },
  { label: 'zip',         kind: 'Function', insertText: 'zip(${1:a}, ${2:b})',
    doc: 'Combine iterables into tuples, stopping at the shortest.' },
  { label: 'map',         kind: 'Function', insertText: 'map(${1:fn}, ${2:iterable})',
    doc: 'Apply fn to each item of iterable. Returns an iterator.' },
  { label: 'filter',      kind: 'Function', insertText: 'filter(${1:fn}, ${2:iterable})',
    doc: 'Filter iterable to items where fn(item) is true.' },
  { label: 'sorted',      kind: 'Function', insertText: 'sorted(${1:iterable})',
    doc: 'Return a new sorted list. Optional: key, reverse.' },
  { label: 'reversed',    kind: 'Function', insertText: 'reversed(${1:seq})',
    doc: 'Return a reverse iterator over a sequence.' },
  { label: 'isinstance',  kind: 'Function', insertText: 'isinstance(${1:obj}, ${2:type})',
    doc: 'True if obj is an instance of type (or a tuple of types).' },
  { label: 'issubclass',  kind: 'Function', insertText: 'issubclass(${1:cls}, ${2:type})',
    doc: 'True if cls is a subclass of type.' },
  { label: 'hasattr',     kind: 'Function', insertText: 'hasattr(${1:obj}, ${2:"attr"})',
    doc: 'True if object has an attribute with the given name.' },
  { label: 'getattr',     kind: 'Function', insertText: 'getattr(${1:obj}, ${2:"attr"})',
    doc: 'Get a named attribute from an object. Optional default value.' },
  { label: 'setattr',     kind: 'Function', insertText: 'setattr(${1:obj}, ${2:"attr"}, ${3:value})',
    doc: 'Set a named attribute on an object.' },
  { label: 'delattr',     kind: 'Function', insertText: 'delattr(${1:obj}, ${2:"attr"})',
    doc: 'Delete a named attribute from an object.' },
  { label: 'callable',    kind: 'Function', insertText: 'callable(${1:obj})',
    doc: 'True if the object appears callable.' },
  { label: 'chr',         kind: 'Function', insertText: 'chr(${1:i})',
    doc: 'Return the string representing the character at Unicode code point i.' },
  { label: 'ord',         kind: 'Function', insertText: 'ord(${1:c})',
    doc: 'Return the Unicode code point of the single character string c.' },
  { label: 'hex',         kind: 'Function', insertText: 'hex(${1:i})',
    doc: 'Convert integer to lowercase hex string (e.g. "0xff").' },
  { label: 'bin',         kind: 'Function', insertText: 'bin(${1:i})',
    doc: 'Convert integer to binary string (e.g. "0b1010").' },
  { label: 'oct',         kind: 'Function', insertText: 'oct(${1:i})',
    doc: 'Convert integer to octal string (e.g. "0o77").' },
  { label: 'id',          kind: 'Function', insertText: 'id(${1:obj})',
    doc: 'Return the identity (memory address) of an object.' },
  { label: 'hash',        kind: 'Function', insertText: 'hash(${1:obj})',
    doc: 'Return the hash value of an object.' },
  { label: 'repr',        kind: 'Function', insertText: 'repr(${1:obj})',
    doc: 'Return a string containing a printable representation of an object.' },
  { label: 'dir',         kind: 'Function', insertText: 'dir(${1:obj})',
    doc: 'Return a list of names in current scope, or attributes of object.' },
  { label: 'vars',        kind: 'Function', insertText: 'vars(${1:obj})',
    doc: 'Return the __dict__ attribute of an object.' },
  { label: 'globals',     kind: 'Function', insertText: 'globals()',
    doc: 'Return the current global symbol table as a dict.' },
  { label: 'locals',      kind: 'Function', insertText: 'locals()',
    doc: 'Return the current local symbol table as a dict.' },
  { label: 'open',        kind: 'Function', insertText: 'open(${1:file}, ${2:"r"})',
    doc: 'Open a file. Modes: r, w, a, rb, wb, r+, w+. Returns a file object.' },
  { label: 'iter',        kind: 'Function', insertText: 'iter(${1:obj})',
    doc: 'Return an iterator for an object.' },
  { label: 'next',        kind: 'Function', insertText: 'next(${1:iter})',
    doc: 'Return the next item from an iterator.' },
  { label: 'format',      kind: 'Function', insertText: 'format(${1:value}, ${2:""})',
    doc: 'Format a value using the given format spec string.' },
  { label: 'eval',        kind: 'Function', insertText: 'eval(${1:expr})',
    doc: 'Evaluate a Python expression string and return the result.' },
  { label: 'exec',        kind: 'Function', insertText: 'exec(${1:code})',
    doc: 'Execute a Python code string in the current scope.' },
  { label: 'compile',     kind: 'Function', insertText: 'compile(${1:src}, ${2:"<string>"}, ${3:"exec"})',
    doc: 'Compile source into a code object. Modes: exec, eval, single.' },
  { label: 'super',       kind: 'Function', insertText: 'super()',
    doc: 'Return a proxy object that delegates method calls to a parent class.' },

  // -- MicroPython built-in types ---------------------------------------------
  { label: 'int',         kind: 'Class', insertText: 'int(${1:x})',
    doc: 'Convert to integer. int(x, base=10) for strings.' },
  { label: 'float',       kind: 'Class', insertText: 'float(${1:x})',
    doc: 'Convert to floating-point number.' },
  { label: 'str',         kind: 'Class', insertText: 'str(${1:x})',
    doc: 'Convert to string. str(object, encoding) for bytes.' },
  { label: 'bool',        kind: 'Class', insertText: 'bool(${1:x})',
    doc: 'Convert to boolean (True or False).' },
  { label: 'list',        kind: 'Class', insertText: 'list(${1:iterable})',
    doc: 'Create a mutable list from an iterable, or an empty list.' },
  { label: 'dict',        kind: 'Class', insertText: 'dict()',
    doc: 'Create a dictionary. dict(key=value, …) or dict(mapping).' },
  { label: 'tuple',       kind: 'Class', insertText: 'tuple(${1:iterable})',
    doc: 'Create an immutable tuple from an iterable.' },
  { label: 'set',         kind: 'Class', insertText: 'set(${1:iterable})',
    doc: 'Create a mutable set from an iterable.' },
  { label: 'frozenset',   kind: 'Class', insertText: 'frozenset(${1:iterable})',
    doc: 'Create an immutable set from an iterable.' },
  { label: 'bytes',       kind: 'Class', insertText: 'bytes(${1:source})',
    doc: 'Immutable sequence of bytes. bytes(n) → n zero bytes; bytes(iterable).' },
  { label: 'bytearray',   kind: 'Class', insertText: 'bytearray(${1:source})',
    doc: 'Mutable sequence of bytes. Same constructor forms as bytes.' },
  { label: 'memoryview',  kind: 'Class', insertText: 'memoryview(${1:obj})',
    doc: 'Memory view of a buffer-protocol object (bytes, bytearray, array).' },
  { label: 'slice',       kind: 'Class', insertText: 'slice(${1:stop})',
    doc: 'Slice object. slice(stop) or slice(start, stop[, step]).' },
  { label: 'object',      kind: 'Class', insertText: 'object',
    doc: 'Base class for all Python objects.' },
  { label: 'type',        kind: 'Function', insertText: 'type(${1:obj})',
    doc: 'Return the type of an object, or create a new type class.' },
  { label: 'property',    kind: 'Function', insertText: 'property(${1:fget})',
    doc: 'Create a property descriptor. Used as @property decorator.' },
  { label: 'staticmethod', kind: 'Function', insertText: 'staticmethod(${1:fn})',
    doc: 'Mark a method as a static method. Used as @staticmethod.' },
  { label: 'classmethod', kind: 'Function', insertText: 'classmethod(${1:fn})',
    doc: 'Mark a method as a class method. Used as @classmethod.' },
  { label: 'NotImplemented', kind: 'Constant',
    doc: 'Returned by binary special methods to indicate the operation is not implemented for the given types.' },
  { label: 'Ellipsis',    kind: 'Constant',
    doc: 'The Ellipsis singleton (same as the literal …). Used as a placeholder.' },

  // -- MicroPython exceptions -------------------------------------------------
  { label: 'Exception',         kind: 'Class', doc: 'Base class for all non-system-exiting exceptions.' },
  { label: 'BaseException',     kind: 'Class', doc: 'Base class for all built-in exceptions.' },
  { label: 'ArithmeticError',   kind: 'Class', doc: 'Base class for arithmetic exceptions (OverflowError, ZeroDivisionError).' },
  { label: 'LookupError',       kind: 'Class', doc: 'Base class for lookup exceptions (IndexError, KeyError).' },
  { label: 'TypeError',         kind: 'Class', doc: 'Raised when an operation is applied to an object of inappropriate type.' },
  { label: 'ValueError',        kind: 'Class', doc: 'Raised when an argument has the right type but an inappropriate value.' },
  { label: 'OSError',           kind: 'Class', doc: 'Raised for OS / filesystem errors. errno attribute gives the error code.' },
  { label: 'IOError',           kind: 'Class', doc: 'Alias for OSError.' },
  { label: 'RuntimeError',      kind: 'Class', doc: 'Raised when an error is detected that does not fit any other category.' },
  { label: 'StopIteration',     kind: 'Class', doc: 'Raised by next() (and iterators) to signal no more items.' },
  { label: 'KeyboardInterrupt', kind: 'Class', doc: 'Raised when Ctrl+C is pressed.' },
  { label: 'SystemExit',        kind: 'Class', doc: 'Raised by sys.exit(). Not derived from Exception.' },
  { label: 'AttributeError',    kind: 'Class', doc: 'Raised when an attribute reference or assignment fails.' },
  { label: 'NameError',         kind: 'Class', doc: 'Raised when a local or global name is not found.' },
  { label: 'ImportError',       kind: 'Class', doc: 'Raised when an import fails.' },
  { label: 'IndexError',        kind: 'Class', doc: 'Raised when a sequence index is out of range.' },
  { label: 'KeyError',          kind: 'Class', doc: 'Raised when a mapping key is not found.' },
  { label: 'MemoryError',       kind: 'Class', doc: 'Raised when an operation runs out of memory.' },
  { label: 'NotImplementedError', kind: 'Class', doc: 'Raised when an abstract method is not overridden.' },
  { label: 'OverflowError',     kind: 'Class', doc: 'Raised when an arithmetic result is too large to be represented.' },
  { label: 'ZeroDivisionError', kind: 'Class', doc: 'Raised when dividing by zero.' },
  { label: 'AssertionError',    kind: 'Class', doc: 'Raised when an assert statement fails.' },
  { label: 'SyntaxError',       kind: 'Class', doc: 'Raised for Python syntax errors.' },
  { label: 'GeneratorExit',     kind: 'Class', doc: 'Raised inside a generator when .close() is called.' },
  { label: 'UnicodeError',      kind: 'Class', doc: 'Raised for Unicode-related encoding/decoding errors.' },

  // -- Importable modules -----------------------------------------------------
  { label: 'math',    kind: 'Module', doc: 'Mathematical functions. Import: import math\nOr: from math import sin, cos, pi' },
  { label: 'time',    kind: 'Module', doc: 'Time and delays. Import: import time\nKey: time.ticks_ms(), time.sleep_ms()' },
  { label: 'random',  kind: 'Module', doc: 'Random numbers. Import: import random\nKey: random.random(), random.randint(a, b)' },
  { label: 'os',      kind: 'Module', doc: 'Operating system interface. Import: import os\nKey: os.listdir(), os.stat(), os.mkdir()' },
  { label: 'sys',     kind: 'Module', doc: 'System-specific params. Import: import sys\nKey: sys.path, sys.exit(), sys.version' },
  { label: 'gc',      kind: 'Module', doc: 'Garbage collector. Import: import gc\nKey: gc.collect(), gc.mem_free()' },
  { label: 'json',    kind: 'Module', doc: 'JSON encode/decode. Import: import json\nKey: json.dumps(obj), json.loads(s)' },
  { label: 'machine', kind: 'Module', doc: 'Hardware access. Import: import machine\nKey: machine.Pin, machine.PWM, machine.ADC' },
  { label: 'struct',  kind: 'Module', doc: 'Binary data pack/unpack. Import: import struct\nKey: struct.pack(fmt, …), struct.unpack(fmt, buf)' },
  { label: 're',      kind: 'Module', doc: 'Regular expressions. Import: import re\nKey: re.match(), re.search(), re.compile()' },
  { label: 'io',      kind: 'Module', doc: 'I/O stream utilities. Import: import io\nKey: io.StringIO(), io.BytesIO()' },
  { label: 'network', kind: 'Module', doc: 'WiFi/network interface. Import: import network\nKey: network.WLAN(network.STA_IF)' },
  { label: 'uasyncio', kind: 'Module', doc: 'Asynchronous I/O. Import: import uasyncio\nKey: uasyncio.run(), uasyncio.sleep_ms()' },

  // -- Badge bundled modules (simulator/modules) ------------------------------
  { label: 'easing',   kind: 'Module', doc: 'Easing / tweening functions (Robert Penner set). Import: import easing\nEach takes x in 0.0–1.0 and returns the eased value. e.g. easing.easeOutBounce(0.5)' },
  { label: 'wifi',     kind: 'Module', doc: 'WiFi connection helper. Import: import wifi\nKey: wifi.connect(ssid, psk), wifi.is_connected(), wifi.ip(). (Simulator always reports connected.)' },
  { label: 'requests', kind: 'Module', doc: 'HTTP requests (fetch-backed). Import: import requests\nKey: requests.get(url), requests.post(url, json=…). Returns a Response with .status_code, .text, .json().' },
  { label: 'fetch',    kind: 'Module', doc: 'Asynchronous file/stream fetching. Import: import fetch\nKey: fetch.AsyncFetch(host).fetch(path); poll .update() until AsyncFetch.DONE.' },
  { label: 'pimoroni', kind: 'Module', doc: 'Pimoroni hardware helpers. Import: import pimoroni\nKey: pimoroni.Button, pimoroni.RGBLED, pimoroni.Analog, pimoroni.PID, pimoroni.Buzzer.' },
  { label: 'board',    kind: 'Module', doc: 'Board pin labels pulled into scope (from machine.Pin.board). Import: import board\nAccess named pins, e.g. board.LED_R.' },
  { label: 'urllib',   kind: 'Module', doc: 'URL handling. Import: import urllib.urequest\nKey: urllib.urequest.urlopen(url).read().' },
];

/* -- Member completions, keyed by the identifier before the dot --------------
   Add entries here whenever "X." should show a completion list.              */
export const MEMBERS = {

  // -- Badgeware: screen / image ----------------------------------------------
  screen: [
    { label: 'width',        kind: 'Property', doc: 'Display width in pixels (160 in LORES, 320 in HIRES).' },
    { label: 'height',       kind: 'Property', doc: 'Display height in pixels (120 in LORES, 240 in HIRES).' },
    { label: 'pen',          kind: 'Property', doc: 'Current draw color. Assign a color value: screen.pen = color.rgb(255, 0, 0).' },
    { label: 'font',         kind: 'Property', doc: 'Current font (pixel_font or font instance). Default: rom_font.sins.' },
    { label: 'clip',         kind: 'Property', doc: 'Current clip rect (rect). Assign to restrict drawing area.' },
    { label: 'antialias',    kind: 'Property', doc: 'Anti-aliasing mode: OFF, X2, or X4.' },
    { label: 'clear',        kind: 'Method', insertText: 'clear()',
      doc: 'Fill the screen with the current pen color.' },
    { label: 'text',         kind: 'Method', insertText: 'text(${1:text}, ${2:x}, ${3:y})',
      doc: 'Draw text string at position (x, y). Pass font size as 4th arg for vector fonts.' },
    { label: 'shape',        kind: 'Method', insertText: 'shape(${1:poly})',
      doc: 'Draw a filled polygon (returned by shape.* constructors).' },
    { label: 'blit',         kind: 'Method', insertText: 'blit(${1:source}, ${2:pos})',
      doc: 'Blit another image onto this one. Args: source (image), pos (vec2 or rect).' },
    { label: 'window',       kind: 'Method', insertText: 'window(${1:x}, ${2:y}, ${3:w}, ${4:h})',
      doc: 'Create a sub-image view of this canvas. Returns an image.' },
    { label: 'measure_text', kind: 'Method', insertText: 'measure_text(${1:text})',
      doc: 'Measure text in the current font. Returns (width, height).' },
    { label: 'line',         kind: 'Method', insertText: 'line(${1:x1}, ${2:y1}, ${3:x2}, ${4:y2})',
      doc: 'Draw a line from (x1,y1) to (x2,y2) with the current pen.' },
    { label: 'rectangle',   kind: 'Method', insertText: 'rectangle(${1:x}, ${2:y}, ${3:w}, ${4:h})',
      doc: 'Draw a filled rectangle. Also accepts a single rect argument.' },
    { label: 'circle',      kind: 'Method', insertText: 'circle(${1:cx}, ${2:cy}, ${3:r})',
      doc: 'Draw a filled circle at (cx, cy) with radius r.' },
    { label: 'triangle',    kind: 'Method', insertText: 'triangle(${1:x1}, ${2:y1}, ${3:x2}, ${4:y2}, ${5:x3}, ${6:y3})',
      doc: 'Draw a filled triangle.' },
    { label: 'get',         kind: 'Method', insertText: 'get(${1:x}, ${2:y})',
      doc: 'Get the color of a pixel at (x, y).' },
    { label: 'put',         kind: 'Method', insertText: 'put(${1:x}, ${2:y})',
      doc: 'Set the color of a pixel at (x, y) to the current pen.' },
    { label: 'blur',        kind: 'Method', insertText: 'blur(${1:radius})',
      doc: 'Apply a box blur in-place. Args: radius (int).' },
    { label: 'dither',      kind: 'Method', insertText: 'dither()',
      doc: 'Apply dithering in-place.' },
    { label: 'onebit',      kind: 'Method', insertText: 'onebit()',
      doc: 'Convert to 1-bit black/white in-place.' },
    { label: 'monochrome',  kind: 'Method', insertText: 'monochrome()',
      doc: 'Convert to monochrome in-place using the current pen.' },
    { label: 'shapes',      kind: 'Method', insertText: 'shapes(${1:shapes_list})',
      doc: 'Draw a list/tuple of shapes in one call with the current pen.' },
    { label: 'blit_hspan',  kind: 'Method', insertText: 'blit_hspan(${1:source}, ${2:x}, ${3:y}, ${4:w})',
      doc: 'Blit a horizontal span from another image.' },
    { label: 'blit_vspan',  kind: 'Method', insertText: 'blit_vspan(${1:source}, ${2:x}, ${3:y}, ${4:h})',
      doc: 'Blit a vertical span from another image.' },
    { label: 'batch',       kind: 'Method', insertText: 'batch(${1:fn})',
      doc: 'Execute fn with deferred rendering for performance.' },
    { label: 'fill_rule',   kind: 'Property', doc: 'Winding fill rule: image.EVEN_ODD or image.NON_ZERO (default).' },
  ],

  // -- Badgeware: badge -------------------------------------------------------
  badge: [
    { label: 'mode',          kind: 'Method', insertText: 'mode(${1:LORES | VSYNC})',
      doc: 'Get or set the display mode. Combine flags with |:\n  LORES (160×120), HIRES (320×240), VSYNC\n  FAST_UPDATE, FULL_UPDATE, MEDIUM_UPDATE, DITHER' },
    { label: 'clear',         kind: 'Method', insertText: 'clear()',
      doc: 'Fill screen with badge.default_clear, reset pen to badge.default_pen.' },
    { label: 'poll',          kind: 'Method', insertText: 'poll()',
      doc: 'Update button state. Called automatically each frame by _update().' },
    { label: 'update',        kind: 'Method', insertText: 'update()',
      doc: 'Flip display buffer + poll buttons. Use in simple blocking loops instead of the update() pattern.' },
    { label: 'pressed',       kind: 'Method', insertText: 'pressed()',
      doc: 'Buttons pressed this frame. Returns a set; pass a button constant to get True/False.' },
    { label: 'held',          kind: 'Method', insertText: 'held()',
      doc: 'Buttons currently held. Returns a set; pass a button constant to get True/False.' },
    { label: 'released',      kind: 'Method', insertText: 'released()',
      doc: 'Buttons released this frame. Returns a set; pass a button constant to get True/False.' },
    { label: 'changed',       kind: 'Method', insertText: 'changed()',
      doc: 'Buttons whose state changed this frame. Returns a set; pass a button constant to get True/False.' },
    { label: 'ticks',         kind: 'Property', doc: 'Milliseconds since startup (int).' },
    { label: 'ticks_delta',   kind: 'Property', doc: 'Milliseconds elapsed since last badge.poll() call (int).' },
    { label: 'model',         kind: 'Property', doc: 'Badge model name: "tufty", "badger", or "blinky".' },
    { label: 'uid',           kind: 'Property', doc: 'Unique hardware ID (hex string).' },
    { label: 'resolution',    kind: 'Property', doc: '(width, height) tuple for the current display mode.' },
    { label: 'default_pen',   kind: 'Property', doc: 'Default pen color restored by badge.clear().' },
    { label: 'default_clear', kind: 'Property', doc: 'Background fill color used by badge.clear().' },
    { label: 'battery_voltage', kind: 'Method', insertText: 'battery_voltage()',
      doc: 'Battery voltage in volts (float).' },
    { label: 'battery_level', kind: 'Method', insertText: 'battery_level()',
      doc: 'Estimated battery percentage 0–100 (int).' },
    { label: 'usb_connected', kind: 'Method', insertText: 'usb_connected()',
      doc: 'True if a USB cable is connected (bool).' },
    { label: 'is_charging',   kind: 'Method', insertText: 'is_charging()',
      doc: 'True if the battery is currently charging (bool). Requires USB to be connected.' },
    { label: 'disk_free',     kind: 'Method', insertText: 'disk_free()',
      doc: 'Disk usage for a mount point. Returns (total, used, free) in bytes. Args: mountpoint="/system".' },
    { label: 'light_level',   kind: 'Method', insertText: 'light_level()',
      doc: 'Raw u16 ambient light sensor reading (Tufty only). Raises RuntimeError on unsupported models.' },
    { label: 'caselights',    kind: 'Method', insertText: 'caselights(${1:value})',
      doc: 'Get/set case LED brightness. Pass one value (all LEDs) or four values. Range 0.0–1.0.' },
    { label: 'sleep',         kind: 'Method', insertText: 'sleep(${1:duration})',
      doc: 'Enter dormant mode. Args: duration in seconds (optional). Wakes on button or RTC alarm.' },
    { label: 'wake_reason',   kind: 'Method', insertText: 'wake_reason()',
      doc: 'Reason the badge woke from sleep (powman constant).' },
    { label: 'woken_by_button', kind: 'Method', insertText: 'woken_by_button()',
      doc: 'True if the badge was woken by a button press (bool).' },
    { label: 'pressed_to_wake', kind: 'Method', insertText: 'pressed_to_wake(${1:button})',
      doc: 'True if a specific button triggered the wake. Args: button constant.' },
    { label: 'woken_by_reset', kind: 'Method', insertText: 'woken_by_reset()',
      doc: 'True if woken by hardware reset (bool).' },
  ],

  // -- Badgeware: shape module ------------------------------------------------
  shape: [
    // -- Shape factories (static) ----------------------------------------------
    { label: 'rectangle',        kind: 'Function', insertText: 'rectangle(${1:x}, ${2:y}, ${3:w}, ${4:h})',
      doc: 'Filled rectangle. Args: x, y, w, h — or a single rect object.' },
    { label: 'rounded_rectangle', kind: 'Function',
      insertText: 'rounded_rectangle(${1:x}, ${2:y}, ${3:w}, ${4:h}, ${5:r1}, ${6:r2}, ${7:r3}, ${8:r4})',
      doc: 'Rounded rectangle. Args: x, y, w, h, corner radii (TL, TR, BR, BL) — or rect + radii.' },
    { label: 'circle',           kind: 'Function', insertText: 'circle(${1:x}, ${2:y}, ${3:r})',
      doc: 'Circle. Args: x, y, radius — or a vec2 centre and radius.' },
    { label: 'ellipse',          kind: 'Function', insertText: 'ellipse(${1:x}, ${2:y}, ${3:rx}, ${4:ry})',
      doc: 'Ellipse. Args: x, y, x-radius, y-radius — or a vec2 centre and radii.' },
    { label: 'line',             kind: 'Function', insertText: 'line(${1:x1}, ${2:y1}, ${3:x2}, ${4:y2})',
      doc: 'Stroked line. Args: x1, y1, x2, y2 (or vec2 pair). Optional: thickness.' },
    { label: 'arc',              kind: 'Function', insertText: 'arc(${1:x}, ${2:y}, ${3:inner_r}, ${4:outer_r}, ${5:from_angle}, ${6:to_angle})',
      doc: 'Arc / annular sector. Args: x, y, inner_radius, outer_radius, from_angle, to_angle. Angles in degrees.' },
    { label: 'pie',              kind: 'Function', insertText: 'pie(${1:x}, ${2:y}, ${3:r}, ${4:from_angle}, ${5:to_angle})',
      doc: 'Pie / sector slice. Args: x, y, radius, from_angle, to_angle. Angles in degrees.' },
    { label: 'star',             kind: 'Function', insertText: 'star(${1:x}, ${2:y}, ${3:points}, ${4:outer_r}, ${5:inner_r})',
      doc: 'Star polygon. Args: x, y, num_points (int), outer_radius, inner_radius.' },
    { label: 'squircle',         kind: 'Function', insertText: 'squircle(${1:x}, ${2:y}, ${3:size})',
      doc: 'Squircle (super-ellipse). Args: x, y, size. Optional: n (exponent, default 4).' },
    { label: 'regular_polygon',  kind: 'Function', insertText: 'regular_polygon(${1:x}, ${2:y}, ${3:r}, ${4:sides})',
      doc: 'Regular polygon. Args: x, y, radius, sides (int).' },
    { label: 'custom',           kind: 'Function', insertText: 'custom(${1:path})',
      doc: 'Custom polygon from a list of vec2 points. Pass additional lists for holes.' },
    { label: 'path',             kind: 'Function', insertText: 'path()',
      doc: 'Create an empty path builder for constructing custom shapes.' },
    // -- Shape instance methods ------------------------------------------------
    { label: 'stroke',           kind: 'Method', insertText: 'stroke(${1:width})',
      doc: 'Return the stroked outline of this shape.\nArgs: width (float). Optional: join_type (shape.JOIN_MITER etc.), miter_limit.' },
    { label: 'bounds',           kind: 'Method', insertText: 'bounds()',
      doc: 'Return the bounding rect of this shape.' },
    // -- Shape/path constants --------------------------------------------------
    { label: 'ALIGN_OUTER',      kind: 'Constant', doc: 'Stroke alignment: outside the path.' },
    { label: 'ALIGN_INNER',      kind: 'Constant', doc: 'Stroke alignment: inside the path.' },
    { label: 'ALIGN_CENTER',     kind: 'Constant', doc: 'Stroke alignment: centered on the path.' },
    { label: 'PATH_CLOSED',      kind: 'Constant', doc: 'Path is closed (endpoint connected to start).' },
    { label: 'PATH_OPEN',        kind: 'Constant', doc: 'Path is open (endpoint not connected).' },
    { label: 'JOIN_MITER',       kind: 'Constant', doc: 'Stroke join: miter (sharp corner).' },
    { label: 'JOIN_ROUND',       kind: 'Constant', doc: 'Stroke join: rounded corner.' },
    { label: 'JOIN_BEVEL',       kind: 'Constant', doc: 'Stroke join: bevelled (flat cut).' },
    { label: 'CAP_BUTT',         kind: 'Constant', doc: 'Stroke cap: flat, ends at the endpoint.' },
    { label: 'CAP_ROUND',        kind: 'Constant', doc: 'Stroke cap: rounded semicircle.' },
    { label: 'CAP_SQUARE',       kind: 'Constant', doc: 'Stroke cap: square, extends past the endpoint.' },
  ],

  // -- Badgeware: color module ------------------------------------------------
  color: [
    { label: 'rgb',         kind: 'Function', insertText: 'rgb(${1:r}, ${2:g}, ${3:b})',
      doc: 'Create a color from RGB values (0–255 each). Optional 4th arg: alpha (0–255).' },
    { label: 'hsv',         kind: 'Function', insertText: 'hsv(${1:h}, ${2:s}, ${3:v})',
      doc: 'Create a color from HSV components (0.0–1.0 each).' },
    { label: 'white',       kind: 'Property', doc: 'White.' },
    { label: 'black',       kind: 'Property', doc: 'Black.' },
    { label: 'red',         kind: 'Property', doc: 'Red.' },
    { label: 'green',       kind: 'Property', doc: 'Green.' },
    { label: 'blue',        kind: 'Property', doc: 'Blue.' },
    { label: 'grey',        kind: 'Property', doc: 'Grey.' },
    { label: 'light_grey',  kind: 'Property', doc: 'Light grey.' },
    { label: 'dark_grey',   kind: 'Property', doc: 'Dark grey.' },
    { label: 'orange',      kind: 'Property', doc: 'Orange.' },
    { label: 'yellow',      kind: 'Property', doc: 'Yellow.' },
    { label: 'cyan',        kind: 'Property', doc: 'Cyan.' },
    { label: 'lime',        kind: 'Property', doc: 'Lime green.' },
    { label: 'navy',        kind: 'Property', doc: 'Navy blue.' },
    { label: 'grape',       kind: 'Property', doc: 'Grape / purple.' },
    { label: 'brown',       kind: 'Property', doc: 'Brown.' },
    { label: 'taupe',       kind: 'Property', doc: 'Taupe.' },
    { label: 'smoke',       kind: 'Property', doc: 'Smoke (pale grey-blue).' },
    { label: 'latte',       kind: 'Property', doc: 'Latte (warm beige).' },
    { label: 'transparent', kind: 'Property', doc: 'Fully transparent (alpha 0).' },
  ],

  // -- Badgeware: text module -------------------------------------------------
  text: [
    { label: 'draw',     kind: 'Method', insertText: 'draw(${1:image}, ${2:text})',
      doc: 'Draw word-wrapped text into an image.\nArgs: image, text (str), bounds=None (rect), line_spacing=1, word_spacing=1, size=24.\nReturns the bounding rect of drawn text.' },
    { label: 'scroll',   kind: 'Method', insertText: 'scroll(${1:text})',
      doc: 'Create a scrolling-text update() function.\nArgs: text (str), font_face=None, font_size=None, target=None, speed=25, gap=None, align="middle".\nReturns an update function.' },
    { label: 'tokenise', kind: 'Method', insertText: 'tokenise(${1:image}, ${2:text})',
      doc: 'Tokenise text into a list for manual layout. Returns a token list compatible with text.draw().' },
  ],

  // -- Badgeware: rom_font ----------------------------------------------------
  rom_font: [
    { label: 'sins',     kind: 'Property', doc: 'ROM pixel font: sins (default system font).' },
    { label: 'absolute', kind: 'Property', doc: 'ROM pixel font: absolute.' },
    { label: 'vest',     kind: 'Property', doc: 'ROM pixel font: vest.' },
    { label: 'nope',     kind: 'Property', doc: 'ROM pixel font: nope.' },
    { label: 'match',    kind: 'Property', doc: 'ROM pixel font: match.' },
    { label: 'winds',    kind: 'Property', doc: 'ROM pixel font: winds.' },
    { label: 'hungry',   kind: 'Property', doc: 'ROM pixel font: hungry.' },
    { label: 'memo',     kind: 'Property', doc: 'ROM pixel font: memo.' },
    { label: 'fear',     kind: 'Property', doc: 'ROM pixel font: fear.' },
  ],

  // -- Badgeware: rtc ---------------------------------------------------------
  rtc: [
    { label: 'datetime',         kind: 'Method', insertText: 'datetime()',
      doc: 'Get or set datetime. Returns (year, month, day, hour, minute, second, weekday).\nPass a tuple to set: rtc.datetime((2025, 1, 1, 12, 0, 0, 2)).' },
    { label: 'localtime_to_rtc', kind: 'Method', insertText: 'localtime_to_rtc()',
      doc: 'Write current system time to the hardware RTC chip.' },
    { label: 'rtc_to_localtime', kind: 'Method', insertText: 'rtc_to_localtime()',
      doc: 'Read the hardware RTC and set the system clock.' },
    { label: 'time_from_ntp',    kind: 'Method', insertText: 'time_from_ntp()',
      doc: 'Fetch current time via NTP and sync to RTC. Requires network.' },
    { label: 'set_timer',        kind: 'Method', insertText: 'set_timer(${1:ticks})',
      doc: 'Start a countdown timer. Args: ticks (int), enable_interrupt=True.' },
    { label: 'timer_elapsed',    kind: 'Method', insertText: 'timer_elapsed()',
      doc: 'True if the timer has elapsed. Clears the timer flag.' },
    { label: 'set_alarm',        kind: 'Method', insertText: 'set_alarm(hours=${1:0}, minutes=${2:0})',
      doc: 'Set a relative wake alarm. Args: hours=0, minutes=0, seconds=0 (relative to now).' },
    { label: 'clear_alarm',      kind: 'Method', insertText: 'clear_alarm()',
      doc: 'Cancel any active alarm and clear interrupt flags.' },
    { label: 'alarm_status',     kind: 'Method', insertText: 'alarm_status()',
      doc: 'True if the alarm has fired (bool).' },
  ],

  // -- Badgeware: image type --------------------------------------------------
  image: [
    { label: 'load',      kind: 'Method',   insertText: 'load(${1:file})',
      doc: 'Load an image from a file path. Returns an image.' },
    { label: 'OFF',       kind: 'Constant', doc: 'Anti-aliasing off.' },
    { label: 'X2',        kind: 'Constant', doc: '2× anti-aliasing supersample.' },
    { label: 'X4',        kind: 'Constant', doc: '4× anti-aliasing supersample.' },
    { label: 'width',     kind: 'Property', doc: 'Width in pixels.' },
    { label: 'height',    kind: 'Property', doc: 'Height in pixels.' },
    { label: 'pen',       kind: 'Property', doc: 'Current draw color.' },
    { label: 'font',      kind: 'Property', doc: 'Current font.' },
    { label: 'clip',      kind: 'Property', doc: 'Clip rect (rect). Assign to restrict drawing.' },
    { label: 'antialias', kind: 'Property', doc: 'Anti-aliasing mode: OFF, X2, or X4.' },
    { label: 'clear',     kind: 'Method',   insertText: 'clear()',
      doc: 'Fill with the current pen color.' },
    { label: 'text',      kind: 'Method',   insertText: 'text(${1:text}, ${2:x}, ${3:y})',
      doc: 'Draw text at (x, y).' },
    { label: 'shape',     kind: 'Method',   insertText: 'shape(${1:poly})',
      doc: 'Draw a filled polygon.' },
    { label: 'blit',      kind: 'Method',   insertText: 'blit(${1:source}, ${2:pos})',
      doc: 'Blit another image. Args: source (image), pos (vec2 or rect).' },
    { label: 'window',    kind: 'Method',   insertText: 'window(${1:x}, ${2:y}, ${3:w}, ${4:h})',
      doc: 'Create a sub-image view.' },
    { label: 'measure_text', kind: 'Method', insertText: 'measure_text(${1:text})',
      doc: 'Measure text dimensions. Returns (width, height).' },
    { label: 'rectangle',  kind: 'Method', insertText: 'rectangle(${1:x}, ${2:y}, ${3:w}, ${4:h})',
      doc: 'Draw a filled rectangle. Also accepts a single rect argument.' },
    { label: 'circle',     kind: 'Method', insertText: 'circle(${1:cx}, ${2:cy}, ${3:r})',
      doc: 'Draw a filled circle at (cx, cy) with radius r.' },
    { label: 'triangle',   kind: 'Method', insertText: 'triangle(${1:x1}, ${2:y1}, ${3:x2}, ${4:y2}, ${5:x3}, ${6:y3})',
      doc: 'Draw a filled triangle.' },
    { label: 'get',        kind: 'Method', insertText: 'get(${1:x}, ${2:y})',
      doc: 'Get the color of a pixel at (x, y).' },
    { label: 'put',        kind: 'Method', insertText: 'put(${1:x}, ${2:y})',
      doc: 'Set the color of a pixel at (x, y) to the current pen.' },
    { label: 'blur',       kind: 'Method', insertText: 'blur(${1:radius})',
      doc: 'Apply a box blur in-place. Args: radius (int).' },
    { label: 'dither',     kind: 'Method', insertText: 'dither()',
      doc: 'Apply dithering in-place.' },
    { label: 'onebit',     kind: 'Method', insertText: 'onebit()',
      doc: 'Convert to 1-bit black/white in-place.' },
    { label: 'monochrome', kind: 'Method', insertText: 'monochrome()',
      doc: 'Convert to monochrome in-place using the current pen.' },
    { label: 'shapes',     kind: 'Method', insertText: 'shapes(${1:shapes_list})',
      doc: 'Draw a list/tuple of shapes in one call with the current pen.' },
    { label: 'load_into',  kind: 'Method', insertText: 'load_into(${1:file})',
      doc: 'Load an image file into this buffer in-place (no allocation).' },
    { label: 'blit_hspan', kind: 'Method', insertText: 'blit_hspan(${1:source}, ${2:x}, ${3:y}, ${4:w})',
      doc: 'Blit a horizontal span from another image.' },
    { label: 'blit_vspan', kind: 'Method', insertText: 'blit_vspan(${1:source}, ${2:x}, ${3:y}, ${4:h})',
      doc: 'Blit a vertical span from another image.' },
    { label: 'batch',      kind: 'Method', insertText: 'batch(${1:fn})',
      doc: 'Execute fn with deferred rendering for performance.' },
    { label: 'fill_rule',  kind: 'Property', doc: 'Winding fill rule: image.EVEN_ODD or image.NON_ZERO (default).' },
    { label: 'EVEN_ODD',   kind: 'Constant', doc: 'Fill rule: even-odd winding (holes in overlapping paths).' },
    { label: 'NON_ZERO',   kind: 'Constant', doc: 'Fill rule: non-zero winding (default).' },
    { label: 'NEAREST',    kind: 'Constant', doc: 'Texture filter: nearest-neighbour (pixelated, fastest).' },
    { label: 'BILINEAR',   kind: 'Constant', doc: 'Texture filter: bilinear interpolation (smooth).' },
    { label: 'BICUBIC',    kind: 'Constant', doc: 'Texture filter: bicubic interpolation (highest quality, slowest).' },
  ],

  // -- Badgeware: loop --------------------------------------------------------
  loop: [
    { label: 'ticks',    kind: 'Property', doc: 'Milliseconds elapsed since this loop started.' },
    { label: 'progress', kind: 'Property', doc: 'Loop progress 0.0–1.0 (only meaningful when duration was set).' },
    { label: 'result',   kind: 'Property', doc: 'Return value from the update function (set when the loop exits).' },
    { label: 'duration', kind: 'Property', doc: 'Total loop duration in ms (or None for infinite).' },
  ],

  // -- Badgeware: State -------------------------------------------------------
  State: [
    { label: 'save',   kind: 'Method', insertText: 'save(${1:app}, ${2:data})',
      doc: 'Save a dict to /state/{app}.json.' },
    { label: 'load',   kind: 'Method', insertText: 'load(${1:app}, ${2:defaults})',
      doc: 'Load state, updating defaults dict in-place. Returns True if a saved file was found.' },
    { label: 'modify', kind: 'Method', insertText: 'modify(${1:app}, ${2:data})',
      doc: 'Merge data dict into existing saved state and re-save.' },
    { label: 'delete', kind: 'Method', insertText: 'delete(${1:app})',
      doc: 'Delete /state/{app}.json.' },
  ],

  // -- Badgeware: SpriteSheet / AnimatedSprite --------------------------------
  SpriteSheet: [
    { label: 'sprite',    kind: 'Method', insertText: 'sprite(${1:x}, ${2:y})',
      doc: 'Get the image for a single sprite at grid position (column, row).' },
    { label: 'animation', kind: 'Method', insertText: 'animation(${1:x}, ${2:y}, ${3:count})',
      doc: 'Create an AnimatedSprite. Args: x=0, y=0, count=None, horizontal=True.' },
  ],

  AnimatedSprite: [
    { label: 'frame', kind: 'Method', insertText: 'frame(${1:0})',
      doc: 'Get the image for the given frame index (wraps around count).' },
    { label: 'count', kind: 'Method', insertText: 'count()',
      doc: 'Total number of animation frames.' },
  ],

  // -- PicoVector: rect -------------------------------------------------------
  rect: [
    { label: 'x',            kind: 'Property', doc: 'Left edge (float).' },
    { label: 'y',            kind: 'Property', doc: 'Top edge (float).' },
    { label: 'w',            kind: 'Property', doc: 'Width (float).' },
    { label: 'h',            kind: 'Property', doc: 'Height (float).' },
    { label: 'deflate',      kind: 'Method', insertText: 'deflate(${1:amount})',
      doc: 'Return a copy shrunk by amount on each side. deflate(a) or deflate(x, y).' },
    { label: 'inflate',      kind: 'Method', insertText: 'inflate(${1:amount})',
      doc: 'Return a copy grown by amount on each side. inflate(a) or inflate(x, y).' },
    { label: 'intersection', kind: 'Method', insertText: 'intersection(${1:other})',
      doc: 'Return the intersection of this rect with another. Returns an empty rect if they do not overlap.' },
    { label: 'intersects',   kind: 'Method', insertText: 'intersects(${1:other})',
      doc: 'True if this rect overlaps with other (bool).' },
    { label: 'contains',     kind: 'Method', insertText: 'contains(${1:other})',
      doc: 'True if this rect fully contains other rect or point (vec2).' },
    { label: 'empty',        kind: 'Method', insertText: 'empty()',
      doc: 'True if this rect has zero area.' },
    { label: 'offset',       kind: 'Method', insertText: 'offset(${1:x}, ${2:y})',
      doc: 'Return a copy shifted by (x, y). Also accepts a single vec2.' },
  ],

  // -- PicoVector: vec2 -------------------------------------------------------
  vec2: [
    { label: 'x',               kind: 'Property', doc: 'X component (float).' },
    { label: 'y',               kind: 'Property', doc: 'Y component (float).' },
    { label: 'length',          kind: 'Method', insertText: 'length()',
      doc: 'Magnitude (Euclidean length) of this vector.' },
    { label: 'length_squared',  kind: 'Method', insertText: 'length_squared()',
      doc: 'Squared magnitude (faster than length() — no square root).' },
    { label: 'normalized',      kind: 'Method', insertText: 'normalized()',
      doc: 'Return a unit vector in the same direction.' },
    { label: 'perpendicular',   kind: 'Method', insertText: 'perpendicular()',
      doc: 'Return a vector perpendicular to this one (rotated 90°).' },
    { label: 'abs',             kind: 'Method', insertText: 'abs()',
      doc: 'Return component-wise absolute value.' },
    { label: 'dot',             kind: 'Method', insertText: 'dot(${1:other})',
      doc: 'Dot product with another vec2.' },
    { label: 'cross',           kind: 'Method', insertText: 'cross(${1:other})',
      doc: 'Cross product (scalar z-component) with another vec2.' },
    { label: 'distance',        kind: 'Method', insertText: 'distance(${1:other})',
      doc: 'Euclidean distance to another vec2.' },
    { label: 'distance_squared', kind: 'Method', insertText: 'distance_squared(${1:other})',
      doc: 'Squared distance to another vec2 (faster than distance()).' },
    { label: 'angle',           kind: 'Method', insertText: 'angle()',
      doc: 'Angle of this vector in radians (atan2(y, x)).' },
    { label: 'angle_to',        kind: 'Method', insertText: 'angle_to(${1:other})',
      doc: 'Angle from this vector to another, in radians.' },
    { label: 'rotated',         kind: 'Method', insertText: 'rotated(${1:angle})',
      doc: 'Return this vector rotated by angle (radians).' },
    { label: 'lerp',            kind: 'Method', insertText: 'lerp(${1:other}, ${2:t})',
      doc: 'Linear interpolation toward other. t=0 returns self, t=1 returns other.' },
    { label: 'reflect',         kind: 'Method', insertText: 'reflect(${1:normal})',
      doc: 'Reflect this vector around the given normal vec2.' },
    { label: 'clamp_length',    kind: 'Method', insertText: 'clamp_length(${1:max_length})',
      doc: 'Return this vector clamped to at most max_length magnitude.' },
    { label: 'transform',       kind: 'Method', insertText: 'transform(${1:matrix})',
      doc: 'Apply a mat3 transformation to this vector.' },
  ],

  // -- PicoVector: brush ------------------------------------------------------
  brush: [
    { label: 'gradient',  kind: 'Function',
      insertText: 'gradient(${1:brush.LINEAR}, ${2:x1}, ${3:y1}, ${4:x2}, ${5:y2}, ${6:stops})',
      doc: 'Gradient brush. Args: type (brush.LINEAR or brush.RADIAL), x1, y1, x2, y2, stops (list of (position, color) tuples). Optional: transform (mat3).' },
    { label: 'image',     kind: 'Function', insertText: 'image(${1:img})',
      doc: 'Image brush. Args: img (image). Optional: transform (mat3) for positioning.' },
    { label: 'pattern',   kind: 'Function', insertText: 'pattern(${1:c1}, ${2:c2}, ${3:index})',
      doc: 'Checkerboard pattern brush. Args: c1, c2 (colors), index (int) or custom pattern tuple.' },
    { label: 'pixelate',  kind: 'Function', insertText: 'pixelate(${1:size})',
      doc: 'Pixelate effect brush. Args: size (int pixel block size).' },
    { label: 'blur',      kind: 'Function', insertText: 'blur(${1:radius})',
      doc: 'Blur effect brush. Args: radius (int).' },
    { label: 'lighten',   kind: 'Function', insertText: 'lighten(${1:amount})',
      doc: 'Lighten blend brush. Args: amount (int 0–255).' },
    { label: 'darken',    kind: 'Function', insertText: 'darken(${1:amount})',
      doc: 'Darken blend brush. Args: amount (int 0–255).' },
    { label: 'LINEAR',    kind: 'Constant', doc: 'Gradient type: linear (straight gradient along a line).' },
    { label: 'RADIAL',    kind: 'Constant', doc: 'Gradient type: radial (circular gradient from a center point).' },
  ],

  // -- PicoVector: mat3 -------------------------------------------------------
  mat3: [
    { label: 'rotate',          kind: 'Method', insertText: 'rotate(${1:degrees})',
      doc: 'Rotate by degrees. Returns self for chaining.' },
    { label: 'rotate_radians',  kind: 'Method', insertText: 'rotate_radians(${1:radians})',
      doc: 'Rotate by radians. Returns self for chaining.' },
    { label: 'translate',       kind: 'Method', insertText: 'translate(${1:x}, ${2:y})',
      doc: 'Translate by (x, y). Also accepts a single vec2. Returns self for chaining.' },
    { label: 'scale',           kind: 'Method', insertText: 'scale(${1:x}, ${2:y})',
      doc: 'Scale by (x, y). Pass one value to scale uniformly. Returns self for chaining.' },
    { label: 'multiply',        kind: 'Method', insertText: 'multiply(${1:other})',
      doc: 'Multiply this matrix by another mat3. Returns a new mat3.' },
    { label: 'inverse',         kind: 'Method', insertText: 'inverse()',
      doc: 'Return the inverse of this matrix.' },
  ],

  // -- PicoVector: algorithm -------------------------------------------------
  algorithm: [
    { label: 'clip_line', kind: 'Function', insertText: 'clip_line(${1:p1}, ${2:p2}, ${3:bounds})',
      doc: 'Clip a line segment to a rect. Args: p1 (vec2), p2 (vec2), bounds (rect).\nReturns a clipped (p1, p2) tuple, or None if entirely outside.' },
    { label: 'dda',       kind: 'Function', insertText: 'dda(${1:origin}, ${2:angle}, ${3:depth})',
      doc: 'Ray march on a tile grid (DDA). Args: origin (vec2), angle (radians), depth (max tiles).\nUseful for simple raycasting / tile collision.' },
    { label: 'raycast',   kind: 'Function', insertText: 'raycast(${1:origin}, ${2:angle}, ${3:fov}, ${4:rays}, ${5:max_dist}, ${6:map})',
      doc: 'Full 2D raycaster. Args: origin (vec2), angle (radians), fov (radians), rays (int), max_dist, map (bytearray), width, height, screen_width.\nReturns ray hit data.' },
  ],

  // -- MicroPython: math module -----------------------------------------------
  math: [
    { label: 'pi',       kind: 'Constant', doc: 'π ≈ 3.14159265' },
    { label: 'e',        kind: 'Constant', doc: 'e ≈ 2.71828182' },
    { label: 'tau',      kind: 'Constant', doc: 'τ = 2π ≈ 6.28318530' },
    { label: 'inf',      kind: 'Constant', doc: 'Floating-point positive infinity.' },
    { label: 'nan',      kind: 'Constant', doc: 'Floating-point not-a-number.' },
    { label: 'sin',      kind: 'Function', insertText: 'sin(${1:x})',     doc: 'Sine of x (radians).' },
    { label: 'cos',      kind: 'Function', insertText: 'cos(${1:x})',     doc: 'Cosine of x (radians).' },
    { label: 'tan',      kind: 'Function', insertText: 'tan(${1:x})',     doc: 'Tangent of x (radians).' },
    { label: 'asin',     kind: 'Function', insertText: 'asin(${1:x})',    doc: 'Arc sine; result in radians.' },
    { label: 'acos',     kind: 'Function', insertText: 'acos(${1:x})',    doc: 'Arc cosine; result in radians.' },
    { label: 'atan',     kind: 'Function', insertText: 'atan(${1:x})',    doc: 'Arc tangent; result in radians.' },
    { label: 'atan2',    kind: 'Function', insertText: 'atan2(${1:y}, ${2:x})', doc: 'Arc tangent of y/x; handles quadrant correctly.' },
    { label: 'sqrt',     kind: 'Function', insertText: 'sqrt(${1:x})',    doc: 'Square root.' },
    { label: 'pow',      kind: 'Function', insertText: 'pow(${1:x}, ${2:y})', doc: 'x raised to the power y (returns float).' },
    { label: 'exp',      kind: 'Function', insertText: 'exp(${1:x})',     doc: 'e raised to the power x.' },
    { label: 'log',      kind: 'Function', insertText: 'log(${1:x})',     doc: 'Natural log. Optional 2nd arg: base.' },
    { label: 'log2',     kind: 'Function', insertText: 'log2(${1:x})',    doc: 'Base-2 logarithm.' },
    { label: 'log10',    kind: 'Function', insertText: 'log10(${1:x})',   doc: 'Base-10 logarithm.' },
    { label: 'ceil',     kind: 'Function', insertText: 'ceil(${1:x})',    doc: 'Ceiling: smallest integer ≥ x.' },
    { label: 'floor',    kind: 'Function', insertText: 'floor(${1:x})',   doc: 'Floor: largest integer ≤ x.' },
    { label: 'trunc',    kind: 'Function', insertText: 'trunc(${1:x})',   doc: 'Truncate toward zero.' },
    { label: 'fabs',     kind: 'Function', insertText: 'fabs(${1:x})',    doc: 'Absolute value as a float.' },
    { label: 'fmod',     kind: 'Function', insertText: 'fmod(${1:x}, ${2:y})', doc: 'Floating-point remainder of x/y.' },
    { label: 'modf',     kind: 'Function', insertText: 'modf(${1:x})',    doc: 'Return (fractional_part, integer_part) as floats.' },
    { label: 'frexp',    kind: 'Function', insertText: 'frexp(${1:x})',   doc: 'Return (mantissa, exponent) such that x = m * 2**e.' },
    { label: 'ldexp',    kind: 'Function', insertText: 'ldexp(${1:x}, ${2:i})', doc: 'Return x * (2 ** i).' },
    { label: 'isfinite', kind: 'Function', insertText: 'isfinite(${1:x})', doc: 'True if x is finite (not inf or nan).' },
    { label: 'isinf',    kind: 'Function', insertText: 'isinf(${1:x})',   doc: 'True if x is positive or negative infinity.' },
    { label: 'isnan',    kind: 'Function', insertText: 'isnan(${1:x})',   doc: 'True if x is not-a-number.' },
    { label: 'copysign', kind: 'Function', insertText: 'copysign(${1:x}, ${2:y})', doc: 'Return x with the sign of y.' },
    { label: 'degrees',  kind: 'Function', insertText: 'degrees(${1:x})', doc: 'Convert radians to degrees.' },
    { label: 'radians',  kind: 'Function', insertText: 'radians(${1:x})', doc: 'Convert degrees to radians.' },
  ],

  // -- MicroPython: time module -----------------------------------------------
  time: [
    { label: 'sleep',      kind: 'Function', insertText: 'sleep(${1:secs})',
      doc: 'Sleep for the given number of seconds (float supported).' },
    { label: 'sleep_ms',   kind: 'Function', insertText: 'sleep_ms(${1:ms})',
      doc: 'Sleep for the given number of milliseconds.' },
    { label: 'sleep_us',   kind: 'Function', insertText: 'sleep_us(${1:us})',
      doc: 'Sleep for the given number of microseconds.' },
    { label: 'ticks_ms',   kind: 'Function', insertText: 'ticks_ms()',
      doc: 'Return a millisecond counter. Wraps around; use ticks_diff() for elapsed time.' },
    { label: 'ticks_us',   kind: 'Function', insertText: 'ticks_us()',
      doc: 'Return a microsecond counter.' },
    { label: 'ticks_cpu',  kind: 'Function', insertText: 'ticks_cpu()',
      doc: 'Return a CPU-cycle counter (resolution depends on hardware).' },
    { label: 'ticks_diff', kind: 'Function', insertText: 'ticks_diff(${1:new_ticks}, ${2:old_ticks})',
      doc: 'Signed difference between two ticks values, handling wrap-around correctly.' },
    { label: 'ticks_add',  kind: 'Function', insertText: 'ticks_add(${1:ticks}, ${2:delta})',
      doc: 'Add delta to ticks, handling wrap-around.' },
    { label: 'time',       kind: 'Function', insertText: 'time()',
      doc: 'Return seconds since the epoch (1970-01-01 UTC) as an integer.' },
    { label: 'time_ns',    kind: 'Function', insertText: 'time_ns()',
      doc: 'Return nanoseconds since the epoch as an integer.' },
    { label: 'localtime',  kind: 'Function', insertText: 'localtime()',
      doc: 'Return local time as (year, month, day, hour, minute, second, weekday, yearday).' },
    { label: 'gmtime',     kind: 'Function', insertText: 'gmtime()',
      doc: 'Return UTC time as (year, month, day, hour, minute, second, weekday, yearday).' },
    { label: 'mktime',     kind: 'Function', insertText: 'mktime(${1:time_tuple})',
      doc: 'Convert a time tuple (as returned by localtime) to seconds since epoch.' },
  ],

  // -- MicroPython: random module ---------------------------------------------
  random: [
    { label: 'random',      kind: 'Function', insertText: 'random()',
      doc: 'Random float in [0.0, 1.0).' },
    { label: 'randint',     kind: 'Function', insertText: 'randint(${1:a}, ${2:b})',
      doc: 'Random integer N such that a ≤ N ≤ b.' },
    { label: 'randrange',   kind: 'Function', insertText: 'randrange(${1:stop})',
      doc: 'Random integer from range(stop) or range(start, stop[, step]).' },
    { label: 'uniform',     kind: 'Function', insertText: 'uniform(${1:a}, ${2:b})',
      doc: 'Random float N such that a ≤ N ≤ b.' },
    { label: 'choice',      kind: 'Function', insertText: 'choice(${1:seq})',
      doc: 'Random element from a non-empty sequence.' },
    { label: 'shuffle',     kind: 'Function', insertText: 'shuffle(${1:seq})',
      doc: 'Shuffle a mutable sequence in place.' },
    { label: 'seed',        kind: 'Function', insertText: 'seed(${1:n})',
      doc: 'Seed the random number generator.' },
    { label: 'getrandbits', kind: 'Function', insertText: 'getrandbits(${1:k})',
      doc: 'Return a non-negative integer with k random bits.' },
  ],

  // -- MicroPython: os module -------------------------------------------------
  os: [
    { label: 'listdir',  kind: 'Function', insertText: 'listdir(${1:"/"})',
      doc: 'Return a list of names in the directory. Default: current directory.' },
    { label: 'stat',     kind: 'Function', insertText: 'stat(${1:path})',
      doc: 'Return status of a file/directory. Returns (f_type, …, f_size, …).' },
    { label: 'mkdir',    kind: 'Function', insertText: 'mkdir(${1:path})',
      doc: 'Create a directory.' },
    { label: 'rmdir',    kind: 'Function', insertText: 'rmdir(${1:path})',
      doc: 'Remove an empty directory.' },
    { label: 'remove',   kind: 'Function', insertText: 'remove(${1:path})',
      doc: 'Remove (delete) a file.' },
    { label: 'rename',   kind: 'Function', insertText: 'rename(${1:old}, ${2:new})',
      doc: 'Rename a file or directory.' },
    { label: 'getcwd',   kind: 'Function', insertText: 'getcwd()',
      doc: 'Return the current working directory as a string.' },
    { label: 'chdir',    kind: 'Function', insertText: 'chdir(${1:path})',
      doc: 'Change the current directory.' },
    { label: 'uname',    kind: 'Function', insertText: 'uname()',
      doc: 'Return system info namedtuple: sysname, nodename, release, version, machine.' },
    { label: 'urandom',  kind: 'Function', insertText: 'urandom(${1:n})',
      doc: 'Return n random bytes.' },
    { label: 'statvfs',  kind: 'Function', insertText: 'statvfs(${1:path})',
      doc: 'Return filesystem statistics for the path.' },
    { label: 'sync',     kind: 'Function', insertText: 'sync()',
      doc: 'Flush all filesystems.' },
    { label: 'mount',    kind: 'Function', insertText: 'mount(${1:fs}, ${2:path})',
      doc: 'Mount a filesystem object at a path.' },
    { label: 'umount',   kind: 'Function', insertText: 'umount(${1:path})',
      doc: 'Unmount a filesystem at a path.' },
    { label: 'sep',      kind: 'Constant', doc: 'Path separator: "/".' },
  ],

  // -- MicroPython: gc module -------------------------------------------------
  gc: [
    { label: 'collect',   kind: 'Function', insertText: 'collect()',
      doc: 'Run a garbage collection pass.' },
    { label: 'mem_free',  kind: 'Function', insertText: 'mem_free()',
      doc: 'Return free heap memory in bytes.' },
    { label: 'mem_alloc', kind: 'Function', insertText: 'mem_alloc()',
      doc: 'Return heap memory currently allocated in bytes.' },
    { label: 'enable',    kind: 'Function', insertText: 'enable()',
      doc: 'Enable automatic garbage collection.' },
    { label: 'disable',   kind: 'Function', insertText: 'disable()',
      doc: 'Disable automatic garbage collection.' },
    { label: 'threshold', kind: 'Function', insertText: 'threshold(${1:amount})',
      doc: 'Set the allocation threshold (in bytes) that triggers a GC run.' },
    { label: 'isenabled', kind: 'Function', insertText: 'isenabled()',
      doc: 'Return True if automatic GC is enabled.' },
  ],

  // -- MicroPython: json module -----------------------------------------------
  json: [
    { label: 'dumps', kind: 'Function', insertText: 'dumps(${1:obj})',
      doc: 'Serialize obj to a JSON-formatted string.' },
    { label: 'loads', kind: 'Function', insertText: 'loads(${1:s})',
      doc: 'Deserialize a JSON string s to a Python object.' },
    { label: 'dump',  kind: 'Function', insertText: 'dump(${1:obj}, ${2:stream})',
      doc: 'Serialize obj as JSON to a file-like stream.' },
    { label: 'load',  kind: 'Function', insertText: 'load(${1:stream})',
      doc: 'Deserialize JSON from a file-like stream.' },
  ],

  // -- MicroPython: machine module --------------------------------------------
  machine: [
    { label: 'Pin',        kind: 'Class',    insertText: 'Pin(${1:id})',
      doc: 'GPIO pin. Modes: Pin.IN, Pin.OUT, Pin.OPEN_DRAIN.\nOptional: pull=Pin.PULL_UP / Pin.PULL_DOWN.\nExample: p = machine.Pin(0, machine.Pin.OUT)' },
    { label: 'PWM',        kind: 'Class',    insertText: 'PWM(${1:pin})',
      doc: 'PWM output. Methods: freq(hz), duty_u16(0–65535), duty_ns(ns), deinit().' },
    { label: 'ADC',        kind: 'Class',    insertText: 'ADC(${1:pin})',
      doc: 'Analog-to-digital converter. Method: read_u16() → 0–65535.' },
    { label: 'I2C',        kind: 'Class',    insertText: 'I2C(${1:id})',
      doc: 'I2C bus. Methods: scan(), readfrom(addr, n), writeto(addr, buf), readfrom_mem(), writeto_mem().' },
    { label: 'SoftI2C',    kind: 'Class',    insertText: 'SoftI2C(scl=${1:pin}, sda=${2:pin})',
      doc: 'Software I2C on any pins. Same interface as I2C.' },
    { label: 'SPI',        kind: 'Class',    insertText: 'SPI(${1:id})',
      doc: 'SPI bus. Methods: read(n), write(buf), write_readinto(wbuf, rbuf).' },
    { label: 'SoftSPI',    kind: 'Class',    insertText: 'SoftSPI(sck=${1:pin}, mosi=${2:pin}, miso=${3:pin})',
      doc: 'Software SPI on any pins.' },
    { label: 'UART',       kind: 'Class',    insertText: 'UART(${1:id}, ${2:baudrate})',
      doc: 'UART serial. Methods: read(), write(), any(), init(baudrate, bits, parity, stop).' },
    { label: 'Timer',      kind: 'Class',    insertText: 'Timer(${1:id})',
      doc: 'Hardware timer. Methods: init(mode, freq, period, callback), deinit().\nModes: Timer.ONE_SHOT, Timer.PERIODIC.' },
    { label: 'RTC',        kind: 'Class',    insertText: 'RTC()',
      doc: 'Real-time clock. Methods: datetime(tuple), alarm(id, time), irq(trigger, handler).' },
    { label: 'WDT',        kind: 'Class',    insertText: 'WDT(timeout=${1:5000})',
      doc: 'Watchdog timer. Method: feed() to prevent reset.' },
    { label: 'reset',      kind: 'Function', insertText: 'reset()',
      doc: 'Hard-reset the device.' },
    { label: 'soft_reset', kind: 'Function', insertText: 'soft_reset()',
      doc: 'Soft-reset: restart interpreter, keep filesystem mounted.' },
    { label: 'reset_cause', kind: 'Function', insertText: 'reset_cause()',
      doc: 'Return the reset cause constant (PWRON_RESET, WDT_RESET, etc.).' },
    { label: 'bootloader', kind: 'Function', insertText: 'bootloader()',
      doc: 'Enter the bootloader.' },
    { label: 'freq',       kind: 'Function', insertText: 'freq(${1:hz})',
      doc: 'Get or set the CPU frequency in Hz.' },
    { label: 'idle',       kind: 'Function', insertText: 'idle()',
      doc: 'Sleep the CPU until the next interrupt.' },
    { label: 'disable_irq', kind: 'Function', insertText: 'disable_irq()',
      doc: 'Disable all interrupts. Returns the current IRQ state to pass to enable_irq().' },
    { label: 'enable_irq',  kind: 'Function', insertText: 'enable_irq(${1:state})',
      doc: 'Re-enable interrupts with the state returned by disable_irq().' },
    { label: 'unique_id',  kind: 'Function', insertText: 'unique_id()',
      doc: 'Return a bytes object with a unique hardware ID.' },
    { label: 'mem8',       kind: 'Variable', doc: '8-bit memory-mapped register array.' },
    { label: 'mem16',      kind: 'Variable', doc: '16-bit memory-mapped register array.' },
    { label: 'mem32',      kind: 'Variable', doc: '32-bit memory-mapped register array.' },
    { label: 'PWRON_RESET',   kind: 'Constant', doc: 'Reset cause: power-on.' },
    { label: 'HARD_RESET',    kind: 'Constant', doc: 'Reset cause: hard reset.' },
    { label: 'WDT_RESET',     kind: 'Constant', doc: 'Reset cause: watchdog.' },
    { label: 'SOFT_RESET',    kind: 'Constant', doc: 'Reset cause: soft reset.' },
    { label: 'DEEPSLEEP_RESET', kind: 'Constant', doc: 'Reset cause: woke from deep sleep.' },
  ],

  // -- MicroPython: sys module ------------------------------------------------
  sys: [
    { label: 'path',        kind: 'Variable', doc: 'List of directories searched for modules.' },
    { label: 'argv',        kind: 'Variable', doc: 'Command-line argument list.' },
    { label: 'version',     kind: 'Variable', doc: 'MicroPython version string.' },
    { label: 'version_info', kind: 'Variable', doc: 'Version as (major, minor, micro) tuple.' },
    { label: 'platform',    kind: 'Variable', doc: 'Platform identifier: "rp2", "esp32", etc.' },
    { label: 'implementation', kind: 'Variable', doc: 'Implementation details namedtuple.' },
    { label: 'modules',     kind: 'Variable', doc: 'Dict of all currently imported modules.' },
    { label: 'stdin',       kind: 'Variable', doc: 'Standard input stream.' },
    { label: 'stdout',      kind: 'Variable', doc: 'Standard output stream.' },
    { label: 'stderr',      kind: 'Variable', doc: 'Standard error stream.' },
    { label: 'exit',        kind: 'Function', insertText: 'exit(${1:0})',
      doc: 'Exit the interpreter with an optional status code.' },
    { label: 'print_exception', kind: 'Function', insertText: 'print_exception(${1:exc})',
      doc: 'Print an exception with its traceback.' },
  ],

  // -- Badge: easing module ---------------------------------------------------
  // Every function takes x in 0.0–1.0 and returns the eased position.
  easing: [
    { label: 'linear',            kind: 'Function', insertText: 'linear(${1:x})',            doc: 'No easing — returns x unchanged.' },
    { label: 'easeInQuad',        kind: 'Function', insertText: 'easeInQuad(${1:x})',        doc: 'Quadratic ease in (accelerate from 0).' },
    { label: 'easeOutQuad',       kind: 'Function', insertText: 'easeOutQuad(${1:x})',       doc: 'Quadratic ease out (decelerate to 1).' },
    { label: 'easeInOutQuad',     kind: 'Function', insertText: 'easeInOutQuad(${1:x})',     doc: 'Quadratic ease in then out.' },
    { label: 'easeInCubic',       kind: 'Function', insertText: 'easeInCubic(${1:x})',       doc: 'Cubic ease in.' },
    { label: 'easeOutCubic',      kind: 'Function', insertText: 'easeOutCubic(${1:x})',      doc: 'Cubic ease out.' },
    { label: 'easeInOutCubic',    kind: 'Function', insertText: 'easeInOutCubic(${1:x})',    doc: 'Cubic ease in then out.' },
    { label: 'easeInQuart',       kind: 'Function', insertText: 'easeInQuart(${1:x})',       doc: 'Quartic ease in.' },
    { label: 'easeOutQuart',      kind: 'Function', insertText: 'easeOutQuart(${1:x})',      doc: 'Quartic ease out.' },
    { label: 'easeInOutQuart',    kind: 'Function', insertText: 'easeInOutQuart(${1:x})',    doc: 'Quartic ease in then out.' },
    { label: 'easeInQuint',       kind: 'Function', insertText: 'easeInQuint(${1:x})',       doc: 'Quintic ease in.' },
    { label: 'easeOutQuint',      kind: 'Function', insertText: 'easeOutQuint(${1:x})',      doc: 'Quintic ease out.' },
    { label: 'easeInOutQuint',    kind: 'Function', insertText: 'easeInOutQuint(${1:x})',    doc: 'Quintic ease in then out.' },
    { label: 'easeInSine',        kind: 'Function', insertText: 'easeInSine(${1:x})',        doc: 'Sinusoidal ease in.' },
    { label: 'easeOutSine',       kind: 'Function', insertText: 'easeOutSine(${1:x})',       doc: 'Sinusoidal ease out.' },
    { label: 'easeInOutSine',     kind: 'Function', insertText: 'easeInOutSine(${1:x})',     doc: 'Sinusoidal ease in then out.' },
    { label: 'easeInExpo',        kind: 'Function', insertText: 'easeInExpo(${1:x})',        doc: 'Exponential ease in.' },
    { label: 'easeOutExpo',       kind: 'Function', insertText: 'easeOutExpo(${1:x})',       doc: 'Exponential ease out.' },
    { label: 'easeInOutExpo',     kind: 'Function', insertText: 'easeInOutExpo(${1:x})',     doc: 'Exponential ease in then out.' },
    { label: 'easeInCirc',        kind: 'Function', insertText: 'easeInCirc(${1:x})',        doc: 'Circular ease in.' },
    { label: 'easeOutCirc',       kind: 'Function', insertText: 'easeOutCirc(${1:x})',       doc: 'Circular ease out.' },
    { label: 'easeInOutCirc',     kind: 'Function', insertText: 'easeInOutCirc(${1:x})',     doc: 'Circular ease in then out.' },
    { label: 'easeInBack',        kind: 'Function', insertText: 'easeInBack(${1:x})',        doc: 'Back ease in (overshoots backwards at the start).' },
    { label: 'easeOutBack',       kind: 'Function', insertText: 'easeOutBack(${1:x})',       doc: 'Back ease out (overshoots past the end).' },
    { label: 'easeInOutBack',     kind: 'Function', insertText: 'easeInOutBack(${1:x})',     doc: 'Back ease in then out (overshoots both ends).' },
    { label: 'easeInElastic',     kind: 'Function', insertText: 'easeInElastic(${1:x})',     doc: 'Elastic ease in (springy).' },
    { label: 'easeOutElastic',    kind: 'Function', insertText: 'easeOutElastic(${1:x})',    doc: 'Elastic ease out (springy).' },
    { label: 'easeInOutElastic',  kind: 'Function', insertText: 'easeInOutElastic(${1:x})',  doc: 'Elastic ease in then out.' },
    { label: 'easeInBounce',      kind: 'Function', insertText: 'easeInBounce(${1:x})',      doc: 'Bounce ease in.' },
    { label: 'easeOutBounce',     kind: 'Function', insertText: 'easeOutBounce(${1:x})',     doc: 'Bounce ease out.' },
    { label: 'easeInOutBounce',   kind: 'Function', insertText: 'easeInOutBounce(${1:x})',   doc: 'Bounce ease in then out.' },
  ],

  // -- Badge: requests module (fetch-backed HTTP) -----------------------------
  requests: [
    { label: 'get',     kind: 'Function', insertText: 'get(${1:url})',
      doc: 'HTTP GET. Returns a Response. Optional kwargs: headers, auth, timeout.' },
    { label: 'post',    kind: 'Function', insertText: 'post(${1:url}, json=${2:data})',
      doc: 'HTTP POST. Pass data=… (str/bytes) or json=… (object).' },
    { label: 'put',     kind: 'Function', insertText: 'put(${1:url})',     doc: 'HTTP PUT. Returns a Response.' },
    { label: 'patch',   kind: 'Function', insertText: 'patch(${1:url})',   doc: 'HTTP PATCH. Returns a Response.' },
    { label: 'delete',  kind: 'Function', insertText: 'delete(${1:url})',  doc: 'HTTP DELETE. Returns a Response.' },
    { label: 'head',    kind: 'Function', insertText: 'head(${1:url})',    doc: 'HTTP HEAD. Returns a Response.' },
    { label: 'request', kind: 'Function', insertText: 'request(${1:"GET"}, ${2:url})',
      doc: 'Generic request. Args: method, url, data=None, json=None, headers=None, auth=None, timeout=None.' },
    { label: 'Response', kind: 'Class',
      doc: 'HTTP response. Attributes: .status_code, .reason, .headers, .text, .content; methods .json(), .close().' },
  ],

  // -- Badge: wifi module (simulator shim — always connected) -----------------
  wifi: [
    { label: 'connect',      kind: 'Function', insertText: 'connect(${1:"ssid"}, ${2:"password"})',
      doc: 'Connect to a network. Args: ssid, psk, timeout=60, retries=5. Returns True. (Simulator connects instantly.)' },
    { label: 'disconnect',   kind: 'Function', insertText: 'disconnect()',   doc: 'Disconnect from the network.' },
    { label: 'tick',         kind: 'Function', insertText: 'tick()',         doc: 'Advance the connection state machine. Returns True when connected.' },
    { label: 'status',       kind: 'Function', insertText: 'status()',       doc: 'Return (status_code, status_text).' },
    { label: 'get_status',   kind: 'Function', insertText: 'get_status(${1:index})', doc: 'Human-readable text for a status code.' },
    { label: 'is_connected', kind: 'Function', insertText: 'is_connected()', doc: 'True if currently connected (bool).' },
    { label: 'ip',           kind: 'Function', insertText: 'ip()',           doc: 'Current IPv4 address (str) or None.' },
    { label: 'ipv4',         kind: 'Function', insertText: 'ipv4()',         doc: 'Current IPv4 address (str) or None.' },
    { label: 'ipv6',         kind: 'Function', insertText: 'ipv6()',         doc: 'Current IPv6 address (str) or None.' },
    { label: 'subnet',       kind: 'Function', insertText: 'subnet()',       doc: 'Subnet mask (str) or None.' },
    { label: 'gateway',      kind: 'Function', insertText: 'gateway()',      doc: 'Gateway address (str) or None.' },
    { label: 'nameserver',   kind: 'Function', insertText: 'nameserver()',   doc: 'DNS server address (str) or None.' },
  ],

  // -- Badge: fetch module (async streamed downloads) -------------------------
  fetch: [
    { label: 'AsyncFetch',    kind: 'Class', insertText: 'AsyncFetch(${1:host})',
      doc: 'Async fetcher. AsyncFetch(host, port=None, use_tls=True, debug=False).\nCall .fetch(path) then poll .update() until it returns AsyncFetch.DONE.' },
    { label: 'HTTPException', kind: 'Class', doc: 'Raised on HTTP errors during a fetch.' },
  ],

  AsyncFetch: [
    { label: 'fetch',       kind: 'Method', insertText: 'fetch(${1:path})',
      doc: 'Start a fetch. Args: path (relative), file=None, interval=None, headers=None, data=None, method=None, blocking=False.' },
    { label: 'update',      kind: 'Method', insertText: 'update()',   doc: 'Advance the fetch. Returns the current status; compare to AsyncFetch.DONE.' },
    { label: 'finish',      kind: 'Method', insertText: 'finish()',   doc: 'Block (yielding to the event loop) until the fetch is DONE.' },
    { label: 'to_json',     kind: 'Method', insertText: 'to_json()',  doc: 'Parse the fetched stream as JSON.' },
    { label: 'on_complete', kind: 'Method', insertText: 'on_complete(${1:handler})', doc: 'Register a completion callback handler(fetch).' },
    { label: 'on_error',    kind: 'Method', insertText: 'on_error(${1:handler})',    doc: 'Register an error callback handler(fetch).' },
    { label: 'status',      kind: 'Property', doc: 'Current status: AsyncFetch.IDLE / FETCHING / DONE / ERROR.' },
    { label: 'duration',    kind: 'Property', doc: 'Milliseconds since the last update.' },
    { label: 'source',      kind: 'Property', doc: 'The requested path.' },
    { label: 'destination', kind: 'Property', doc: 'Target file path, or None for a stream.' },
    { label: 'http_status', kind: 'Property', doc: 'HTTP response status code.' },
    { label: 'http_response_headers', kind: 'Property', doc: 'Dict of response headers.' },
    { label: 'stream',      kind: 'Property', doc: 'A readable stream over the fetched content.' },
    { label: 'IDLE',        kind: 'Constant', doc: 'Status: idle (0).' },
    { label: 'FETCHING',    kind: 'Constant', doc: 'Status: fetching (1).' },
    { label: 'DONE',        kind: 'Constant', doc: 'Status: done (2).' },
    { label: 'ERROR',       kind: 'Constant', doc: 'Status: error (3).' },
  ],

  // -- Badge: pimoroni module (hardware helpers) ------------------------------
  pimoroni: [
    { label: 'Button',        kind: 'Class', insertText: 'Button(${1:pin})',
      doc: 'Debounced button with repeat/hold. Button(button, invert=True, repeat_time=200, hold_time=1000).\nMethods: .read(), .raw(); property .is_pressed.' },
    { label: 'RGBLED',        kind: 'Class', insertText: 'RGBLED(${1:"LED_R"}, ${2:"LED_G"}, ${3:"LED_B"})',
      doc: 'PWM RGB LED. RGBLED(r, g, b, invert=True). Method: .set_rgb(r, g, b) with 0–255 channels.' },
    { label: 'PWMLED',        kind: 'Class', insertText: 'PWMLED(${1:pin})',
      doc: 'Single brightness-controlled LED. PWMLED(pin, invert=False).\nMethods: .brightness(0.0–1.0), .on(), .off(), .toggle().' },
    { label: 'Analog',        kind: 'Class', insertText: 'Analog(${1:pin})',
      doc: 'Analog input. Analog(pin, amplifier_gain=1, resistor=0, offset=0).\nMethods: .read_voltage(), .read_current().' },
    { label: 'AnalogMux',     kind: 'Class', insertText: 'AnalogMux(${1:addr0})',
      doc: 'Analog multiplexer. AnalogMux(addr0, addr1=None, addr2=None, en=None, muxed_pin=None).\nMethods: .select(addr), .read(), .configure_pull(addr, pull), .disable().' },
    { label: 'Buzzer',        kind: 'Class', insertText: 'Buzzer(${1:pin})',
      doc: 'Piezo buzzer. Method: .set_tone(freq, duty=0.5).' },
    { label: 'PID',           kind: 'Class', insertText: 'PID(${1:kp}, ${2:ki}, ${3:kd}, ${4:sample_rate})',
      doc: 'PID controller. Set .setpoint, then call .calculate(value, value_change=None).' },
    { label: 'ShiftRegister', kind: 'Class', insertText: 'ShiftRegister(${1:clk}, ${2:lat}, ${3:dat})',
      doc: 'Shift register reader. Methods: .read(), .is_set(mask); iterable/indexable for individual bits.' },
    { label: 'NORMAL_DIR',    kind: 'Constant', doc: 'Motor/encoder direction: normal (0x00).' },
    { label: 'REVERSED_DIR',  kind: 'Constant', doc: 'Motor/encoder direction: reversed (0x01).' },
  ],

  // -- Badge: urllib.urequest -------------------------------------------------
  urllib: [
    { label: 'urequest', kind: 'Module', doc: 'Minimal urlopen. import urllib.urequest; urllib.urequest.urlopen(url).' },
  ],
  urequest: [
    { label: 'urlopen', kind: 'Function', insertText: 'urlopen(${1:url})',
      doc: 'Open a URL (fetch-backed). urlopen(url, data=None, method="GET"). Returns a stream with .read()/.readline()/.close() and .status.' },
  ],
};
